name: .NET Core

on:
  push:
    branches: 
      - master
      - homework*
  pull_request:
    branches: 
      - master
    
jobs:
  build:
    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: |
        dotnet restore Homework3\Task1\
        dotnet restore Homework3\Task2\
        dotnet restore Homework3\Task3\
        dotnet restore Homework3\Task4\
        dotnet restore Homework3\Task5\
    
    - name: Build
      run: |
        dotnet build Homework3\Task1\ --configuration Release --no-restore
        dotnet build Homework3\Task2\ --configuration Release --no-restore
        dotnet build Homework3\Task3\ --configuration Release --no-restore
        dotnet build Homework3\Task4\ --configuration Release --no-restore
        dotnet build Homework3\Task5\ --configuration Release --no-restore
    
    - name: Test
      run: |
        dotnet test Homework3\Task1\ --no-restore --verbosity normal
        dotnet test Homework3\Task2\ --no-restore --verbosity normal
        dotnet test Homework3\Task3\ --no-restore --verbosity normal
        dotnet test Homework3\Task4\ --no-restore --verbosity normal
        dotnet test Homework3\Task5\ --no-restore --verbosity normal
